<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_Event</name>
   <tag></tag>
   <elementGuidId>122a68a9-8187-460f-8d6e-484b1b4fb3ba</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>event</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-diary&quot;)/div[1]/div[@class=&quot;osc-container&quot;]/div[@class=&quot;oscc-tbl oscctbl-uploadentry full-width&quot;]/div[@class=&quot;oscct-top full-width&quot;]/div[@class=&quot;occtt-full&quot;]/div[@class=&quot;occttf&quot;]/ul[1]/li[2]/span[@class=&quot;input-event&quot;]/input[@class=&quot;input-text required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
