<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Event</name>
   <tag></tag>
   <elementGuidId>986c5030-1173-460b-9c57-4f0eb6a11ff5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Event</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;order-diary&quot;)/div[1]/div[@class=&quot;osc-container&quot;]/div[@class=&quot;oscc-tbl oscctbl-uploadentry full-width&quot;]/div[@class=&quot;oscct-top full-width&quot;]/div[@class=&quot;occtt-full&quot;]/div[@class=&quot;occttf&quot;]/ul[1]/li[2]/span[@class=&quot;title&quot;]</value>
   </webElementProperties>
</WebElementEntity>
