<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Create Account</name>
   <tag></tag>
   <elementGuidId>006fceb0-e25a-43d4-8a17-f1c0c3d6eb9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'Create Account' or . = 'Create Account')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW9MIIq5laD0ISpqUbOdP8KhMnCgUuXa8eA7JVjYCKqMxmyZ3NvsRLkfAxEbQjNVHTyc9mHVTJA3fE2n81Q2ihyvEjPYjZ5pFI3mj-2BudjByKHbjLfgJdqtJR22uWDTyPHnEsOVcMee4Mwvlfd-2Fqxeshs-3D_NXqVZxi55pyjdNjzv1aWByReXvYRH0lFfVU3FZ-2BLHsN1sjR0Mz1J5FPOUgDycHItGImP793H26gkveB-2FoOKS0-2B3KwVpn1GnCG5WIHkH1dfMYQbVYxFv1Gvz4qBf0f8K2cmXsDEfQe-2FMI0r3NaANAms41ua6vuy6AZ9-2FK-2F26ZF2A8OGf42tx4-2FMu2ulXX-2BtCnSJhyd-2BLkhojwl3ky3J6GTeVUdF-2BVkK141xf6VtL1pmI-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW9MIIq5laD0ISpqUbOdP8KhMnCgUuXa8eA7JVjYCKqMxmyZ3NvsRLkfAxEbQjNVHTyc9mHVTJA3fE2n81Q2ihyvEjPYjZ5pFI3mj-2BudjByKHbjLfgJdqtJR22uWDTyPHnEsOVcMee4Mwvlfd-2Fqxeshs-3D_NXqVZxi55pyjdNjzv1aWByReXvYRH0lFfVU3FZ-2BLHsN1sjR0Mz1J5FPOUgDycHItGImP793H26gkveB-2FoOKS0-2B3KwVpn1GnCG5WIHkH1dfMYQbVYxFv1Gvz4qBf0f8K2cmXsDEfQe-2FMI0r3NaANAms41ua6vuy6AZ9-2FK-2F26ZF2A8OGf42tx4-2FMu2ulXX-2BtCnSJhyd-2BLkhojwl3ky3J6GTeVUdF-2BVkK141xf6VtL1pmI-3D&amp;source=gmail&amp;ust=1549329820112000&amp;usg=AFQjCNHD6fQg8ee0tYPzBs9F9wAXdIg5LA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;:qs&quot;]/div[1]/div/div[2]/div[4]/a</value>
   </webElementProperties>
</WebElementEntity>
