<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_sellerDescription</name>
   <tag></tag>
   <elementGuidId>aedb5eb9-7a88-4624-a090-8449a33fca7d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>merchant-description</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>One of the Philippines’ top pharmaceutical retailer providing easy access to quality and affordable medicines for its numerous customers.</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLR7RMIJS0O7&quot;)/div[@class=&quot;store-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;store-detail-box&quot;]/div[@class=&quot;store-description&quot;]/p[@class=&quot;merchant-description&quot;]</value>
   </webElementProperties>
</WebElementEntity>
