<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>01_ManualDecline</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>382d551d-cd08-4f8d-bac0-0fb55dc266b8</testSuiteGuid>
   <testCaseLink>
      <guid>32c0af99-6081-45d3-bc80-350517789f30</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6972ce23-faa3-4c2c-ab39-1b9dfd57720c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Chat Page/Chat Scenarios/Manual Decline/01_Enquiry</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>00a2e591-145a-40e2-af8e-0d368405f77e</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/Consumer_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>00a2e591-145a-40e2-af8e-0d368405f77e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemA</value>
         <variableId>45bc509c-3bde-438e-a94e-b4bad459b9b7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>00a2e591-145a-40e2-af8e-0d368405f77e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>listName</value>
         <variableId>a7ee560d-5eed-4b1d-bfde-f65a9d855ba7</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>00a2e591-145a-40e2-af8e-0d368405f77e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantity</value>
         <variableId>efd0ec1b-89ff-433e-8273-60d9f7bac661</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>00a2e591-145a-40e2-af8e-0d368405f77e</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>8ea18fd5-5e51-4a38-9b75-fbd7c70c3301</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0a01e0c3-275f-48ef-b802-a7d31a0e7826</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>a62393a3-4381-469b-bf12-d7f7fd2cb21d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5326bce0-9c55-4ba7-916a-c3740c7e890a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Merchant Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>1c9fecd3-037a-4e0c-8460-fc42e2f66584</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Chat Page/Chat Scenarios/Manual Decline/02_CreateOffer</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>657fce6b-dc1d-4404-b239-3b46fa0414dc</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/Consumer_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>657fce6b-dc1d-4404-b239-3b46fa0414dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemA</value>
         <variableId>ef18491d-1ffb-4f18-baee-0d002cae5bb8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>657fce6b-dc1d-4404-b239-3b46fa0414dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>listName</value>
         <variableId>8e22a79e-7c5a-462d-b558-c1fcf8d36ca3</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>657fce6b-dc1d-4404-b239-3b46fa0414dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantity</value>
         <variableId>e624c8ed-12a0-43c3-a1b1-dad008a867bc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>657fce6b-dc1d-4404-b239-3b46fa0414dc</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>price</value>
         <variableId>c2c6b66e-d438-4f28-9c92-51f83a5d60cb</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8593e35d-6f50-459b-918a-6dad87218ea2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>ba92f46a-5b82-4beb-a196-1d8b4b197a57</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9e59d73a-e42f-4bf1-a5b3-e59dd56ed761</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d5027551-88ce-4259-988d-dcdc87cf2124</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Chat Page/Chat Scenarios/Manual Decline/03_DeclineOffer</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>dc1b13dc-03ef-4443-9d0e-3e293c80b0cd</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/Consumer_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>dc1b13dc-03ef-4443-9d0e-3e293c80b0cd</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemA</value>
         <variableId>d1ef4311-eac2-43f6-8420-6a3b3308b561</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>d273e37f-e653-4dc3-8478-bee6e032edc2</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>9e0ae7a8-9c28-4fe1-9723-2c0130d64049</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Merchant Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>48282ccb-d923-41f9-83c7-180163e4d744</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Chat Page/Chat Scenarios/Manual Decline/04_InboxSellerDecline</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d41cec5b-bb5c-4308-a0aa-b2741154621c</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/Consumer_TestData</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d41cec5b-bb5c-4308-a0aa-b2741154621c</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemA</value>
         <variableId>87267b29-f78f-4f5d-90c1-2503a3e4d9cf</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>16e17e8b-2ac0-4898-a3d0-1104843ad4b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Utilities/MERCHANT/Logout</testCaseId>
   </testCaseLink>
</TestSuiteEntity>
