<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>url_https625un.test.arcadier.io</name>
   <tag></tag>
   <elementGuidId>8c9b24c7-a051-4dc6-8399-be418e46fd57</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjk4YqKUFnNzckm-2BXsveA2Na_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMs4QYpAVfhKKDPct9GqblwiKC2mWIVhE8FAGoHXtsOzcAnthfkZN6k7QmUDuAxhApY2dsAKMcBq5lBwjk-2BA2tyoLB0oFXjG71MZGAJ-2BlngWaT3gTvjXbZzXBNRPhKqS80jBCNkv4WaqYBx6ZauZwmb7v-2BLHCBR9TzIqMir694k4m-2F6uZ1YdBVdJVUoSyTjLDsI-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjk4YqKUFnNzckm-2BXsveA2Na_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMs4QYpAVfhKKDPct9GqblwiKC2mWIVhE8FAGoHXtsOzcAnthfkZN6k7QmUDuAxhApY2dsAKMcBq5lBwjk-2BA2tyoLB0oFXjG71MZGAJ-2BlngWaT3gTvjXbZzXBNRPhKqS80jBCNkv4WaqYBx6ZauZwmb7v-2BLHCBR9TzIqMir694k4m-2F6uZ1YdBVdJVUoSyTjLDsI-3D&amp;source=gmail&amp;ust=1571186387079000&amp;usg=AFQjCNFMNECRtGj-2nNom5R71kF6XKguJg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://625un.test.arcadier.io</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:ms&quot;)/div[2]/div[2]/div[2]/div[5]/p[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
