<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Offer from Seller Desc</name>
   <tag></tag>
   <elementGuidId>96f48249-b08b-457b-a1e6-f369a9eb9b18</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[3]/div/div[3]/div[2]/ul/li[6]/p</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div[2]/div[3]/div/div[3]/div[2]/ul/li[6]/p</value>
   </webElementProperties>
</WebElementEntity>
