<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>delivery_Name</name>
   <tag></tag>
   <elementGuidId>26afa656-4447-40e1-b0cd-5466881c1e56</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>th</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;settings-index-container&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;delivery-setting-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;ds-content&quot;]/div[@class=&quot;dsc-table&quot;]/div[@class=&quot;ph-t-table&quot;]/table[@class=&quot;table delivery-set-data&quot;]/thead[1]/tr[1]/th[1]</value>
   </webElementProperties>
</WebElementEntity>
