<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_itemName</name>
   <tag></tag>
   <elementGuidId>22b39ada-dd57-4372-a0b8-4bd1fd9174f5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h4</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>item-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>apple1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;storefront-container&quot;)/div[1]/div[@class=&quot;product-list&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-2 col-sm-4 col-xs-6 xs-mb-15&quot;]/a[@class=&quot;item-box-small&quot;]/div[@class=&quot;item-detail&quot;]/h4[@class=&quot;item-name&quot;]</value>
   </webElementProperties>
</WebElementEntity>
