<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd2</name>
   <tag></tag>
   <elementGuidId>d11c09c7-ac2a-417d-b44f-952478e43d6e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@data-name = 'SP_Drop Down_M2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>SP_Drop Down_M2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additional-desc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SP_Drop Down_M2DD1SP_Drop Down_M2DD2SP_Drop Down_M2DD3SP_Drop Down_M2DD4SP_Drop Down_M2DD5SP_Drop Down_M2DD6SP_Drop Down_M2DD7SP_Drop Down_M2DD8SP_Drop Down_M2DD9SP_Drop Down_M2DD10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customfields&quot;)/div[@class=&quot;col-md-6&quot;]/select[@class=&quot;required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
