<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>dd6</name>
   <tag></tag>
   <elementGuidId>8d768088-a5a3-4f54-a140-7564b82772ab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//select[@data-name = 'SPG_Drop Down_M2']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>SPG_Drop Down_M2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additional-desc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPG_Drop Down_M2DD1SPG_Drop Down_M2DD2SPG_Drop Down_M2DD3SPG_Drop Down_M2DD4SPG_Drop Down_M2DD5SPG_Drop Down_M2DD6SPG_Drop Down_M2DD7SPG_Drop Down_M2DD8SPG_Drop Down_M2DD9SPG_Drop Down_M2DD10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customfields&quot;)/div[@class=&quot;col-md-6&quot;]/select[@class=&quot;required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
