<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_beta</name>
   <tag></tag>
   <elementGuidId>6f368e67-fe09-4240-a7fa-0ba690132d7d</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://bootstrap.arcadier.com/adminportal/images/icon-sidebar/beta.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;no-sub-title&quot;)/div[@class=&quot;pull-left&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page-title&quot;]/h1[1]/sup[1]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
