<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>empty_image top viewed</name>
   <tag></tag>
   <elementGuidId>fce7809f-b772-4d74-865f-9044d3d34d6f</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Areas/User/Assets/core/themes/trillia/images/cannot-found.png</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLKAFAQNC5J3&quot;)/div[1]/div[@class=&quot;dashboard-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;dashboard-content&quot;]/div[@class=&quot;dashboard-tables&quot;]/div[@class=&quot;tbl-dash&quot;]/div[@class=&quot;ph-t-table&quot;]/span[@class=&quot;graph-empty&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
