<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>texlabel_Price</name>
   <tag></tag>
   <elementGuidId>123fdcd0-c1e3-43c9-9923-652be1475d1a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1,007.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;chat-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;chat-box-parent&quot;]/div[@class=&quot;right-message-bar&quot;]/ul[@class=&quot;messanger-outer&quot;]/li[@class=&quot;send-msg&quot;]/div[@class=&quot;msg-box&quot;]/div[1]/div[@class=&quot;offer-box&quot;]/div[@class=&quot;offer-box-deal&quot;]/div[@class=&quot;offer-box-sent&quot;]/span[@class=&quot;price&quot;]</value>
   </webElementProperties>
</WebElementEntity>
