<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_quantity</name>
   <tag></tag>
   <elementGuidId>865aea10-1f43-4441-ab05-e2a17a44b489</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>100</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;chat-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;chat-box-parent&quot;]/div[@class=&quot;right-message-bar&quot;]/ul[@class=&quot;messanger-outer&quot;]/li[@class=&quot;send-msg&quot;]/div[@class=&quot;msg-box&quot;]/div[1]/div[@class=&quot;offer-box&quot;]/div[@class=&quot;offer-box-deal&quot;]/ul[@class=&quot;user-product-container&quot;]/li[@class=&quot;user-product-info-quantity&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
