<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_SentOffer</name>
   <tag></tag>
   <elementGuidId>22bbfbb0-51e1-4818-9669-6755daf4a335</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sent an offer</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;main&quot;]/div[@class=&quot;chat-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;chat-box-parent&quot;]/div[@class=&quot;right-message-bar&quot;]/ul[@class=&quot;messanger-outer&quot;]/li[@class=&quot;send-msg&quot;]/div[@class=&quot;msg-box&quot;]/div[1]/div[@class=&quot;offer-box&quot;]/div[@class=&quot;offer-box-deal&quot;]/div[@class=&quot;offer-box-sent&quot;]/p[1]</value>
   </webElementProperties>
</WebElementEntity>
