<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Create Account</name>
   <tag></tag>
   <elementGuidId>013bd6dd-7c31-418e-b969-4d8714c62a79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjm1L4DCrocuzlkxiyMPNwrMjFxX7WWYZ8-2Fs2D39TB1UzUFviGS2yOsEaH20Gmj4rbYOGwUUJxl3HdfIiGPHeGu4HOO24-2F-2BC6PnF7u1s2YzHUMeoP5y8hmyOoHk1VicwUvFno-2F1kk9e2OCkuSVUzxIQX_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMub1oZyJNJhKrkbCIzD7DavAvvphDfax0xrXEJIBH8ghSCIYVVtIuWqQxgjUDLAlKliGN2PYm-2B9Vomi19GWHnOB1csP2QTlmnpiranLeBj304Aa-2FG4uvuKXS2-2BjdVYoXbvO4zUMOm-2FR174x8lDtbQOh2Ep6PUkIgDdtTVs80FHvLe4MVFJ-2FRb8qI-2BxFV4RXEyw-3D' and (text() = 'Create Account' or . = 'Create Account')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjm1L4DCrocuzlkxiyMPNwrMjFxX7WWYZ8-2Fs2D39TB1UzUFviGS2yOsEaH20Gmj4rbYOGwUUJxl3HdfIiGPHeGu4HOO24-2F-2BC6PnF7u1s2YzHUMeoP5y8hmyOoHk1VicwUvFno-2F1kk9e2OCkuSVUzxIQX_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMub1oZyJNJhKrkbCIzD7DavAvvphDfax0xrXEJIBH8ghSCIYVVtIuWqQxgjUDLAlKliGN2PYm-2B9Vomi19GWHnOB1csP2QTlmnpiranLeBj304Aa-2FG4uvuKXS2-2BjdVYoXbvO4zUMOm-2FR174x8lDtbQOh2Ep6PUkIgDdtTVs80FHvLe4MVFJ-2FRb8qI-2BxFV4RXEyw-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dWwc4SMWk2f3P44yNyFB1Xd6vxx9o-2Bt7I-2Bc10RKi-2ByyeCPmj8iAXiujKfqSHvjAVMf5usFLK1JKbeIy9coKfH-2Bm0qigHqUraQvn5rJCfk4feFnaubpilraX6RNNPvjAv1jn3wKXRW9ia9FxGE-2B7svPWe-2Bv8z10SMjttzIkzdDEY4Y_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwny86uA35o4U4K5f7TlGFL06xOgWSepDstoZuanyupGijzHlK08RoVb8VKNOmg-2FldAZwUAtZlJyNutT8K-2F0I8-2B0o37A-2F0UvBIzFQu545dZynPxcxjGkWTpqG8B07vecxecmUUW8suQitNsucU-2FA-2BiIceUzithrW0uIADrn1R3VyQGGh8dxBaXdplxPW2oXHKJ4-3D&amp;source=gmail&amp;ust=1570763413446000&amp;usg=AFQjCNGdBlRCALr_-wuaZNfs0ssn0ElcLA</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:19m&quot;)/div[2]/div[2]/div[2]/div[4]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
