<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Category 3.1.1</name>
   <tag></tag>
   <elementGuidId>780eb4bb-8970-4c2f-a404-93730ca6d383</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;basic_tab&quot;]/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[3]/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;basic_tab&quot;]/div[2]/div[2]/div/div/div/div/div/div[2]/div/div/div[2]/ul/li[3]/label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
</WebElementEntity>
