<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Checkout 1</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>96aa60b1-4aa6-4099-9532-f606fdd1b282</testSuiteGuid>
   <testCaseLink>
      <guid>2cfa905d-b2a9-4735-9e3c-21c6ebf92a4d</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Utilities/CONSUMER/Consumer Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>ef2f50b0-3ea6-4b20-a2e0-9b167b035c83</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/CONSUMER/Checkout Scenario/search_Item</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>2967dd32-0209-4688-8d94-5cb907c232b4</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/checkoutUN</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>2967dd32-0209-4688-8d94-5cb907c232b4</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemname</value>
         <variableId>6aa3d25a-1606-4fce-b279-88023c372a00</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>897974c6-cde9-4113-9887-b5b85a4cc809</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Checkout Scenario/AddItem_to_EvaluationWidget</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>165c3ead-c77e-44b3-a177-8902faab8733</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/CONSUMER/checkoutUN</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>165c3ead-c77e-44b3-a177-8902faab8733</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>itemname</value>
         <variableId>a2ee6505-f8d5-4a9a-adad-5a6d9386ff9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>165c3ead-c77e-44b3-a177-8902faab8733</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>quantityvalue</value>
         <variableId>1cfff8df-6641-4272-b862-c7794cbf478b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>165c3ead-c77e-44b3-a177-8902faab8733</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>listname</value>
         <variableId>6eb83117-4451-4020-a59d-8b7533b4f3f9</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>7a3f2d31-154b-45bd-a191-293d71a0dbda</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Checkout Scenario/OrderNow_EvaluationTable</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>78b43a1e-8a8c-4cad-beb8-b96c6c11ff45</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>672a8e89-8519-4f21-b469-48dbfb29b7ae</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/CONSUMER/Checkout Scenario/Checkout_DefaultFlow</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>27acd25f-1886-4c6a-b12d-a9e96bcbb48c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>3837321a-cfa0-4722-8409-540e33eb10c8</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7427df10-8980-4389-9be7-bab7868bc0ad</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
