<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linktext_resetUrl</name>
   <tag></tag>
   <elementGuidId>6d937004-5869-4488-a410-0ebdebd590e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[2]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div[2]/div[2]/div[3]/p[2]/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[2]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div[2]/div[2]/div[3]/p[2]/a[count(. | //a[(text() = 'https://625un.test.arcadier.io/user/marketplace/resetpassword?userId=62646&amp;code=KRex%2b9RZXUfY18LFew7lTnnToE2Kh4DAw7HK%2fXqbjfjdL0L59KBj99pmn52BJj%2b58if1L2bsEudyuoIhb7YHS3lJ5gs0mSWolLesDjjXbm6rJkM9QuMqSVqfr1D2U1vEi12qVvhIm8MXxypcN2Ju6NuWGbo%3d' or . = 'https://625un.test.arcadier.io/user/marketplace/resetpassword?userId=62646&amp;code=KRex%2b9RZXUfY18LFew7lTnnToE2Kh4DAw7HK%2fXqbjfjdL0L59KBj99pmn52BJj%2b58if1L2bsEudyuoIhb7YHS3lJ5gs0mSWolLesDjjXbm6rJkM9QuMqSVqfr1D2U1vEi12qVvhIm8MXxypcN2Ju6NuWGbo%3d')]) = count(//a[(text() = 'https://625un.test.arcadier.io/user/marketplace/resetpassword?userId=62646&amp;code=KRex%2b9RZXUfY18LFew7lTnnToE2Kh4DAw7HK%2fXqbjfjdL0L59KBj99pmn52BJj%2b58if1L2bsEudyuoIhb7YHS3lJ5gs0mSWolLesDjjXbm6rJkM9QuMqSVqfr1D2U1vEi12qVvhIm8MXxypcN2Ju6NuWGbo%3d' or . = 'https://625un.test.arcadier.io/user/marketplace/resetpassword?userId=62646&amp;code=KRex%2b9RZXUfY18LFew7lTnnToE2Kh4DAw7HK%2fXqbjfjdL0L59KBj99pmn52BJj%2b58if1L2bsEudyuoIhb7YHS3lJ5gs0mSWolLesDjjXbm6rJkM9QuMqSVqfr1D2U1vEi12qVvhIm8MXxypcN2Ju6NuWGbo%3d')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dWwc4SMWk2f3P44yNyFB1Xd6vxx9o-2Bt7I-2Bc10RKi-2ByyeCsqNzRa3mNYis8EdoiRzRiRTjS8EOrkDm4aG2Nt0nH0PK9ZkHZd-2Flsv7Z0eIW577kEfVGxmccBuMwle25LTLP-2FLajpAjD6Fj5m3HviUUU61vEbLbL3vZlP7t-2B9EbqVJAgi-2Fh5obNvgbirD-2BYCxwmVr6oY-2BezC4t4y9-2Fs1bdq-2BFfZnik4yQ4ON2sIxpjzAYUCdT-2FijJA-2Fn3z5-2BiD0CFFsM4rrIQ8NcBL0FmOdbi80kOuZJyOQkErERIi-2FiLA-2BrqzYTP9QuKC-2BUq6SmZhy5BCvBdgZXXLvxpERJw-2Fp6Sg8-2FwPw-3D_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMvdarYvwC6VPfmrOdJnnhog-2Bg3Rn-2FwEGb5xFavpH0BvtxOva47UrBVJ6Sd4ikQYx2I6VToMLtE0hnmVSWtQtemDEgv09euANGn-2BLdeOg335cJs6eA0nEg1lE9bXGsS8SxjhJIIYgKjPqyIgC3bgEx-2FjqcGaVfLRj4I-2BFhCxWvfxH-2F1ueIxPYFil8rSWlC30BmQ-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[2]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div[2]/div[2]/div[3]/p[2]/a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://625un.test.arcadier.io/user/marketplace/resetpassword?userId=62646&amp;code=KRex%2b9RZXUfY18LFew7lTnnToE2Kh4DAw7HK%2fXqbjfjdL0L59KBj99pmn52BJj%2b58if1L2bsEudyuoIhb7YHS3lJ5gs0mSWolLesDjjXbm6rJkM9QuMqSVqfr1D2U1vEi12qVvhIm8MXxypcN2Ju6NuWGbo%3d</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[2]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div[2]/div[2]/div[3]/p[2]/a</value>
   </webElementProperties>
</WebElementEntity>
