<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_SPG_Drop Down_M1DD1SPG_</name>
   <tag></tag>
   <elementGuidId>e048b9e2-f2aa-4133-83fb-e2b752c66eac</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>required</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-name</name>
      <type>Main</type>
      <value>SPG_Drop Down_M1</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>additional-desc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SPG_Drop Down_M1DD1SPG_Drop Down_M1DD2SPG_Drop Down_M1DD3SPG_Drop Down_M1DD4SPG_Drop Down_M1DD5SPG_Drop Down_M1DD6SPG_Drop Down_M1DD7SPG_Drop Down_M1DD8SPG_Drop Down_M1DD9SPG_Drop Down_M1DD10</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customfields&quot;)/div[@class=&quot;col-md-6&quot;]/select[@class=&quot;required&quot;]</value>
   </webElementProperties>
</WebElementEntity>
