<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>icon_delete</name>
   <tag></tag>
   <elementGuidId>1918491f-d828-47c4-8c35-e4da4aaf81fd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;basic_tab&quot;]/div[2]/div[3]/div/div/div[2]/div/div/a/i</value>
   </webElementProperties>
</WebElementEntity>
