<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_purchasable</name>
   <tag></tag>
   <elementGuidId>0db3d249-8e49-4373-b373-4c61c450f51a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[4]/div/div/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div/div/table/thead/tr/th[6]/span/label[count(. | //label[@for = 'checkAvailPurchaseable']) = count(//label[@for = 'checkAvailPurchaseable'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>checkAvailPurchaseable</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[4]/div/div/div/div[2]/div/div[3]/div/div[2]/div[2]/div/div/div/table/thead/tr/th[6]/span/label</value>
   </webElementProperties>
</WebElementEntity>
