<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>image_question</name>
   <tag></tag>
   <elementGuidId>ece38cde-1243-4223-a1d9-133382fdb67a</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/Areas/Admin/Assets/core/images/Question.svg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLPCB8R01I1L&quot;)/div[@class=&quot;col-sm-9 main-content ann&quot;]/div[@class=&quot;page-content page-announce&quot;]/div[@class=&quot;col-md-7&quot;]/div[@class=&quot;follow-sec&quot;]/div[1]/div[@class=&quot;follow-right&quot;]/div[@class=&quot;faqArea align-center&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
