<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Invite Merchant Sub Account</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-10-16T08:28:21</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>f54abe60-671f-44f5-b889-450e59c22f5e</testSuiteGuid>
   <testCaseLink>
      <guid>ac5d61eb-458a-468d-a7b0-98afe76382dd</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADMIN/EDM/Gmail Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>6af66282-8587-466f-a28f-6452ec9cdf85</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADMIN/EDM/Verify Invite Merchant Sub Account</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>e91c02be-daab-4638-a04b-77ed6fedfc40</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EDM/Start Selling</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>e91c02be-daab-4638-a04b-77ed6fedfc40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>recipient</value>
         <variableId>71116008-2c97-43f9-b917-f4ed7a130b0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e91c02be-daab-4638-a04b-77ed6fedfc40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Subject</value>
         <variableId>66f5f9c7-4536-4e40-adc5-1e1f6037cd9b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e91c02be-daab-4638-a04b-77ed6fedfc40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Cc</value>
         <variableId>355b4531-21e2-4369-945b-f39f1ffe1be0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>e91c02be-daab-4638-a04b-77ed6fedfc40</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Bcc</value>
         <variableId>c41f4040-7539-4694-862b-f51e8c5910c0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>a4fe41af-224f-4dae-87e8-366b0bf5af7b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>99bc5719-902e-4719-8170-e857bf3fea80</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
