<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>New Message from Consumer</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-10-16T10:48:13</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>68568c94-5d07-441c-9adf-88d097590473</testSuiteGuid>
   <testCaseLink>
      <guid>e8d6f711-2bb5-41fd-9f8c-aadbfee50de4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/ADMIN/EDM/Gmail Login</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>29ce45cd-81a7-47a6-a68b-aa300198e8b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADMIN/EDM/Verify Message from Buyer Content</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>fbd1edde-ae6a-4e4a-bdd9-2c6822868dbf</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EDM/Start Selling</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>fbd1edde-ae6a-4e4a-bdd9-2c6822868dbf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>recipient</value>
         <variableId>49585f6c-704a-4f2e-b010-dbd892984b1b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fbd1edde-ae6a-4e4a-bdd9-2c6822868dbf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Cc</value>
         <variableId>7011656f-b405-434c-8769-8b5e81a8a9bf</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fbd1edde-ae6a-4e4a-bdd9-2c6822868dbf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Bcc</value>
         <variableId>44014d6d-f776-4a07-970b-578d653dd2f0</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>fbd1edde-ae6a-4e4a-bdd9-2c6822868dbf</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Subject</value>
         <variableId>7d306424-bbe1-40e8-acb8-66bb26ab7cff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>20c5e698-7087-438c-8d36-b450b39b94d2</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>c9494b3f-850f-4345-8f79-a3d0e61af4e8</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
