<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Order Confirmation</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <lastRun>2019-10-17T08:42:41</lastRun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <testSuiteGuid>c082eca3-f645-42d4-83b6-fce8faf46187</testSuiteGuid>
   <testCaseLink>
      <guid>cb353356-e513-4a36-9bf0-c2996e55b04a</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/ADMIN/EDM/Login Gmail Buyer</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>609c176e-be66-48df-8979-e1de50f584d8</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/ADMIN/EDM/Verify Received Order content</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>4e05678e-6d8f-4756-af45-b1deaebffb32</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/EDM/From Seller</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>4e05678e-6d8f-4756-af45-b1deaebffb32</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>recipient</value>
         <variableId>210bbc8f-4c92-45dd-9cf0-594b6d623fce</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e05678e-6d8f-4756-af45-b1deaebffb32</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Cc</value>
         <variableId>38dae7f2-47ad-4382-9b11-0228c43a8432</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e05678e-6d8f-4756-af45-b1deaebffb32</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Bcc</value>
         <variableId>3c5ce5fd-a19d-4ee7-9a0e-02ee7d75ecb9</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>4e05678e-6d8f-4756-af45-b1deaebffb32</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>Subject</value>
         <variableId>f6dcbd21-c6b1-44a1-8edf-f858f1249b05</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>efd27c20-bce3-400f-8c6f-a26be9dffcb1</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d847561f-7b5a-4f75-aefd-599c201a572e</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
