<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_opt1</name>
   <tag></tag>
   <elementGuidId>dda3975c-69f9-4363-a1b4-6217003f6e13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;dropdown-opt-draggble&quot;]/li[1]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
