<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_option2</name>
   <tag></tag>
   <elementGuidId>9d3b3f5e-bc31-449b-a699-ecd9bd2fb0a2</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div[3]/div/div[1]/div[2]/div/form/div/div[9]/div/ul/li[2]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[4]/div/div[1]/div[2]/div/form/div/div[8]/div/ul/li[2]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div[3]/div/div[1]/div[2]/div/form/div/div[9]/div/ul/li[2]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
