<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textfield_option1</name>
   <tag></tag>
   <elementGuidId>2a438be3-032b-456a-805e-c7b67345ab8a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div[3]/div/div[1]/div[2]/div/form/div/div[9]/div/ul/li[1]/div/div[2]/input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div[2]/div[4]/div/div[1]/div[2]/div/form/div/div[8]/div/ul/li[1]/div/div[2]/input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div[3]/div/div[1]/div[2]/div/form/div/div[9]/div/ul/li[1]/div/div[2]/input</value>
   </webElementProperties>
</WebElementEntity>
