<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_HTML</name>
   <tag></tag>
   <elementGuidId>1338c86a-dae4-4c42-b18c-e3a1a6cc2112</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>HTML</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;panel-box box-email-template in-relatition&quot;]/div[@class=&quot;panel-box-content&quot;]/div[@class=&quot;form-group&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
