<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Password</name>
   <tag></tag>
   <elementGuidId>85eab764-e7d6-45da-8f43-8eb40fea2f68</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Password</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-info&quot;)/div[@class=&quot;page-content&quot;]/div[@class=&quot;gutter-wrapper&quot;]/div[@class=&quot;detail-area panel-box acc-info-top section-account&quot;]/div[@class=&quot;account-info-personal-bil-sec&quot;]/div[@class=&quot;detail-btm&quot;]/div[@class=&quot;detail-col-wrapper&quot;]/div[@class=&quot;account-info-form&quot;]/div[@class=&quot;fields-group&quot;]/label[1]</value>
   </webElementProperties>
</WebElementEntity>
