<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>label_customfield_pdfvalues</name>
   <tag></tag>
   <elementGuidId>564715d8-4c7b-4481-b09b-db4625088ef1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[2]/div[1]/div/div[2]/div[3]/div[2]/div[17]/span[2]/p/span/a</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[2]/div[1]/div/div[2]/div[3]/div[2]/div[17]/span[2]/p/span/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://1112un.test.arcadier.io/pdf/items/370453bd-984d-491b-a142-52d8dbbdebe7-je4z02674s_1mb.pdf</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>1mb.pdf</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[2]/div[1]/div/div[2]/div[3]/div[2]/div[17]/span[2]/p/span/a</value>
   </webElementProperties>
</WebElementEntity>
