<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_totalvalue</name>
   <tag></tag>
   <elementGuidId>be39e8d9-133a-497b-afce-9fd50af82e89</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>value</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>23.50</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MyPrintDiv&quot;)/div[@class=&quot;orderdetail-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;order-box&quot;]/div[@class=&quot;order-detail-row&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-md-4 pull-right&quot;]/div[@class=&quot;br-info&quot;]/div[@class=&quot;sum-ammount total text-right&quot;]/div[@class=&quot;item-price total-amount&quot;]/span[@class=&quot;value&quot;]</value>
   </webElementProperties>
</WebElementEntity>
