<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>logo_marketplace</name>
   <tag></tag>
   <elementGuidId>a26362fd-853d-460b-84f8-ad6a32311836</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://1029un.test.arcadier.io/images/logo-1029un.test.arcadier.io.jpeg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;login-page&quot;)/div[@class=&quot;login-container&quot;]/div[@class=&quot;icon-logo&quot;]/div[@class=&quot;icon-logo&quot;]/img[1]</value>
   </webElementProperties>
</WebElementEntity>
