<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_Create Account</name>
   <tag></tag>
   <elementGuidId>349e243d-e4c6-4629-8e7b-c6e183a32757</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjm1L4DCrocuzlkxiyMPNwrMjFxX7WWYZ8-2Fs2D39TB1UzUFviGS2yOsEaH20Gmj4rbbd9O7VGFJrRQJa6Ic8nxfntoK7CgBh14NBN95Fiehf3W2DROW4yBkXHk2fLxNzZ81wvuDV3MQgo0ryHXQqolph_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMu-2FNtRA9BgaSkKcRA0EL1m1d-2F0TPaPR3ADt1a5-2BsTdpS7dThZ8L2WHrW2JdC0M0EBv9tl-2FdlfrSxo2CCX8w5kfP7oyV8mxwLm40-2F4QnkXPbJ3Gcis12zK-2BTOKFk-2F1EWJiHb8LhegRq2P29isIz2Vqhj9GqSTDb0TVoUR-2F4v6dbs4jsSdM0eoB4BouzJTS3YVrg-3D' and (text() = 'Create Account' or . = 'Create Account')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjm1L4DCrocuzlkxiyMPNwrMjFxX7WWYZ8-2Fs2D39TB1UzUFviGS2yOsEaH20Gmj4rbbd9O7VGFJrRQJa6Ic8nxfntoK7CgBh14NBN95Fiehf3W2DROW4yBkXHk2fLxNzZ81wvuDV3MQgo0ryHXQqolph_-2FlVKhLauYRHm-2FC8Ownvq0M-2FbE54I2y8XhETw2ZJvdMu-2FNtRA9BgaSkKcRA0EL1m1d-2F0TPaPR3ADt1a5-2BsTdpS7dThZ8L2WHrW2JdC0M0EBv9tl-2FdlfrSxo2CCX8w5kfP7oyV8mxwLm40-2F4QnkXPbJ3Gcis12zK-2BTOKFk-2F1EWJiHb8LhegRq2P29isIz2Vqhj9GqSTDb0TVoUR-2F4v6dbs4jsSdM0eoB4BouzJTS3YVrg-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dWwc4SMWk2f3P44yNyFB1Xd6vxx9o-2Bt7I-2Bc10RKi-2ByyeCPmj8iAXiujKfqSHvjAVMf5usFLK1JKbeIy9coKfH-2Bm3Vq0vnvOwyfbflBAsja-2Bp-2FGSUwn-2BV-2BWMX9QwnwjPZGwkKlbIVUAztT6FA8C-2Bc7kI96wRLzU6p1dlhEY7qJbdzC_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwkm-2FvgGRpWCGjAbO5Htn2IK0nlmbLBFty22WViAZlT1FELrTA6mMX8zU271iIoFcmIzRzVTRoaEDTqj7qgTWYaYGeFeQr1RpA7sVL4W8-2BeQZKrPjtWJ8SH1Wm6q-2Fln5mijRQdIcvNvDH6QmJnNF-2BVPNSNob6N2uCOJMpNq6G-2FUHAll4BvNJNClEp9SypM7KJXY-3D&amp;source=gmail&amp;ust=1570759523291000&amp;usg=AFQjCNEqE01NxqZxJ1jDumm6Qq63aILCZw</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Create Account</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:11v&quot;)/div[1]/div[1]/div[2]/div[4]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
