<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linktext_Url</name>
   <tag></tag>
   <elementGuidId>df1af4b2-b1fe-4a18-81a7-ed2f457131e1</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dWwc4SMWk2f3P44yNyFB1Xd4QN6iUMgSmHm2VJ0cA-2FKzy_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwkm-2FvgGRpWCGjAbO5Htn2IKriPxqiTa3cIt-2FE79xO9rDnsDN9xcPtd-2BTfKVllrI5lvZ6588dAhTN7pjnK-2Fu3t0d7CLjxyLFygOA0zeX4f6kdmMq1-2BJOi21kTw19F8-2B5xR4fdX8P2iQ5w16ByvjX01ux1iItk-2B0vFylGukqUIlbHierrSHZLP79weumWkM3Dg6M-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dWwc4SMWk2f3P44yNyFB1Xd4QN6iUMgSmHm2VJ0cA-2FKzy_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwkm-2FvgGRpWCGjAbO5Htn2IKriPxqiTa3cIt-2FE79xO9rDnsDN9xcPtd-2BTfKVllrI5lvZ6588dAhTN7pjnK-2Fu3t0d7CLjxyLFygOA0zeX4f6kdmMq1-2BJOi21kTw19F8-2B5xR4fdX8P2iQ5w16ByvjX01ux1iItk-2B0vFylGukqUIlbHierrSHZLP79weumWkM3Dg6M-3D&amp;source=gmail&amp;ust=1570759523291000&amp;usg=AFQjCNEwyBpTs_4C383O90ru2l9GCtFejQ</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://dncddemo.staging.arcadier.io</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:11v&quot;)/div[1]/div[1]/div[2]/div[5]/p[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
