<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>value_OrderID</name>
   <tag></tag>
   <elementGuidId>eba44a53-dd4f-49a2-bd0a-692522fd3934</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[3]/div[2]/div[2]/div/div[2]/div[3]/div[1]/h3</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[3]/div[2]/div[2]/div/div[2]/div[3]/div[1]/h3</value>
   </webElementProperties>
</WebElementEntity>
