<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_SubTotalvalue</name>
   <tag></tag>
   <elementGuidId>b1dec9f1-e894-4ab9-91d8-74b39ad1cf06</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Sub TotalUSD $ 2,500.00</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:s7&quot;)/div[2]/div[2]/div[2]/div[6]/table[1]/tbody[1]/tr[1]/td[2]/div[1]</value>
   </webElementProperties>
</WebElementEntity>
