<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_START SELLING</name>
   <tag></tag>
   <elementGuidId>b39ebcb1-c2db-4916-a224-30685255c229</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div/div[2]/div[4]/a[count(. | //a[(text() = 'START SELLING' or . = 'START SELLING')]) = count(//a[(text() = 'START SELLING' or . = 'START SELLING')])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW4eEWD3eOuCUNR6YW7lDvgkJIo9m11jncM-2B-2F0AxhLyhRc9ed3x-2FCTfcimu8NdtquKg-3D-3D_QRFaIn3IOl5E0Lv-2FZxAGH710f-2FHbX8Q5r1jdNhszvdlf6BT-2Fr8mbXZTVI1P0Fcpt1SwBc7Z1rGB8KL6489UNL3TO6rbSJcVmeQggt2JBTRoKbWjON3mVNz3U9MMgIXOMjAcXF9Wyti8SKMVYk-2Bfc3d9fog9YeK8qWFtDMQaqQbwhbIlyZPaBdLV4JuhMS4KAC-2F8BVhzW1y0d0T-2BB2oH9VA-3D-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW4eEWD3eOuCUNR6YW7lDvgkJIo9m11jncM-2B-2F0AxhLyhRc9ed3x-2FCTfcimu8NdtquKg-3D-3D_QRFaIn3IOl5E0Lv-2FZxAGH710f-2FHbX8Q5r1jdNhszvdlf6BT-2Fr8mbXZTVI1P0Fcpt1SwBc7Z1rGB8KL6489UNL3TO6rbSJcVmeQggt2JBTRoKbWjON3mVNz3U9MMgIXOMjAcXF9Wyti8SKMVYk-2Bfc3d9fog9YeK8qWFtDMQaqQbwhbIlyZPaBdLV4JuhMS4KAC-2F8BVhzW1y0d0T-2BB2oH9VA-3D-3D&amp;source=gmail&amp;ust=1570757369693000&amp;usg=AFQjCNE0euKzRmUClxwh_urG0jMlGhuW4w</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>START SELLING</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div/div[2]/div[4]/a</value>
   </webElementProperties>
</WebElementEntity>
