<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linktext_url</name>
   <tag></tag>
   <elementGuidId>1bb242bc-7b74-463b-83b9-d2a84e6b7b34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div/div[2]/div[5]/p[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW4eEWD3eOuCUNR6YW7lDvgnY-2FlUULnjyFxXt5vfWacpl_QRFaIn3IOl5E0Lv-2FZxAGH710f-2FHbX8Q5r1jdNhszvdlf6BT-2Fr8mbXZTVI1P0Fcpt60uvp2rulw16ZiwpuyGq-2FTN3-2F2BdkRIeCXMAgmydGWlYASbulS-2BA7lXj6Sv-2BC35Ve7zmopZhNFazt0I426aUQ1fagIDPiPC12acqJCBJzlwZkARrm1EcVjqEONbb6psjHTCQnQ3YxD1h5ARMWQGveQ-3D-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dW4eEWD3eOuCUNR6YW7lDvgnY-2FlUULnjyFxXt5vfWacpl_QRFaIn3IOl5E0Lv-2FZxAGH710f-2FHbX8Q5r1jdNhszvdlf6BT-2Fr8mbXZTVI1P0Fcpt60uvp2rulw16ZiwpuyGq-2FTN3-2F2BdkRIeCXMAgmydGWlYASbulS-2BA7lXj6Sv-2BC35Ve7zmopZhNFazt0I426aUQ1fagIDPiPC12acqJCBJzlwZkARrm1EcVjqEONbb6psjHTCQnQ3YxD1h5ARMWQGveQ-3D-3D&amp;source=gmail&amp;ust=1570757369693000&amp;usg=AFQjCNFH4wCMmoNN-vvM4JYE68Z1N52mTg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://qatrilla.arcadier.io</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html/body/div[7]/div[3]/div/div[2]/div[1]/div[2]/div/div/div/div/div[2]/div/div[1]/div/div[3]/div/table/tr/td[1]/div[2]/div[2]/div/div[3]/div/div/div/div/div/div[1]/div[2]/div[4]/div[3]/div/div[2]/div/div[2]/div[5]/p[2]/a</value>
   </webElementProperties>
</WebElementEntity>
