<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Currency</name>
   <tag></tag>
   <elementGuidId>805aec72-f1e3-41b9-a5a2-82c532b425a3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div[1]/div/div[3]/div[1]/div[1]/div/span[1]/span[2]/div/span[1]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div/div/div[1]/div/div[3]/div[1]/div[1]/div/span[1]/span[2]/div/span[1][count(. | //span[@class = 'currency']) = count(//span[@class = 'currency'])]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>currency</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SGD $ </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[1]/div/div[3]/div[1]/div[1]/div/span[1]/span[2]/div/span[1]</value>
   </webElementProperties>
</WebElementEntity>
