<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_Bcc</name>
   <tag></tag>
   <elementGuidId>4c5615e1-4c7b-4b4f-95a5-a39e53e938bf</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bcc</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;template&quot;)/div[@class=&quot;col-sm-8&quot;]/div[@class=&quot;panel-box box-email-template in-relatition&quot;]/div[@class=&quot;panel-box-content&quot;]/div[@class=&quot;group-cc-bcc&quot;]/div[@class=&quot;form-group form-group-border&quot;]/label[1]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
