<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>togglebutton_timeneeded</name>
   <tag></tag>
   <elementGuidId>601f78cf-a982-4534-8935-2c65c1b2d3a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@id=&quot;contactForm&quot;]/div/div[11]/div/div[2]/div/label/span[2]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;contactForm&quot;]/div/div[11]/div/div[2]/div/label/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>DIV</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;contactForm&quot;]/div/div[11]/div/div[2]/div/label/span[2]</value>
   </webElementProperties>
</WebElementEntity>
