<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>linktext_url</name>
   <tag></tag>
   <elementGuidId>948e47bc-b770-4ee5-8e90-42dfe0d96a9d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = 'https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjk4YqKUFnNzckm-2BXsveA2Na_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwmVhfTt2kJ-2FCcUSFHfyl7P94BJnaEd09l4-2BOFYoDP74oD3PlZRKQ0aX4nf11OgSkFcfrnWMBeRIR0ZC4KujMfyVDZSNqNqIkgJaRqCASLqQPYCIGziB00zzpxT5uLTBI1pvRGzu6ve8JW5X6UBmzS6knwZuzjxjkCpEj5-2FYAszX0-2BVNGjXTZaflLSN4bUWLy8I-3D' and (text() = 'https://625un.test.arcadier.io' or . = 'https://625un.test.arcadier.io')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjk4YqKUFnNzckm-2BXsveA2Na_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwmVhfTt2kJ-2FCcUSFHfyl7P94BJnaEd09l4-2BOFYoDP74oD3PlZRKQ0aX4nf11OgSkFcfrnWMBeRIR0ZC4KujMfyVDZSNqNqIkgJaRqCASLqQPYCIGziB00zzpxT5uLTBI1pvRGzu6ve8JW5X6UBmzS6knwZuzjxjkCpEj5-2FYAszX0-2BVNGjXTZaflLSN4bUWLy8I-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_blank</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-saferedirecturl</name>
      <type>Main</type>
      <value>https://www.google.com/url?q=https://u2507958.ct.sendgrid.net/wf/click?upn%3DllNWqR-2FTpI64syuC183dWwc4SMWk2f3P44yNyFB1Xd4QN6iUMgSmHm2VJ0cA-2FKzy_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwnAq1Cm62uZgtn90eRA-2Fehg7vv-2BEdRZ7r99U9zHHtyCdgZP9Ztnw1-2F0DEFzzhHC57CtNcGjKWnai6WxA5gbaUwOW6lA7Va31zl9CEHGjkzzK8Lbzk7-2FAcoEZ1CpmQorAViA5noCxTHfAQFFopO68NZsR4NM3N-2BRfegsDAHT7fbHmTdKgyUtrCEVr4X5puX6l-2BI-3D&amp;source=gmail&amp;ust=1570759525135000&amp;usg=AFQjCNGtU8X-d7V82lRj27LIkZ51uDFjNg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://625un.test.arcadier.io</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:17s&quot;)/div[2]/div[1]/div[2]/div[8]/p[2]/a[1]</value>
   </webElementProperties>
</WebElementEntity>
