<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_desc2nd</name>
   <tag></tag>
   <elementGuidId>5b7b055e-d620-4682-a14e-67ddaec8c284</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                        You will find setup instructions for the most popular domain providers, but you should read these general instructions first so you have a broad understanding of the process before you begin.
                    </value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;note-sure&quot;)/div[@class=&quot;page-content-btm&quot;]/p[2]</value>
   </webElementProperties>
</WebElementEntity>
