<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_from</name>
   <tag></tag>
   <elementGuidId>f1bd2ec2-ba8f-4d90-b7c0-c098089195d5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gI</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>from:</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;:o2&quot;)/div[@class=&quot;adn ads&quot;]/div[@class=&quot;gs&quot;]/div[@class=&quot;ajA SK&quot;]/div[@class=&quot;ajB gt&quot;]/table[@class=&quot;ajC&quot;]/tbody[1]/tr[@class=&quot;UszGxc ajv&quot;]/td[@class=&quot;gG&quot;]/span[@class=&quot;gI&quot;]</value>
   </webElementProperties>
</WebElementEntity>
