<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Icon_TrashInsideTable</name>
   <tag></tag>
   <elementGuidId>82bdcfe7-5918-4e49-8c6e-58eb70dcfb59</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div[4]/div/div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[4]/div/div/div[1]/div/div/a/i</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[4]/div/div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[4]/div/div/div[1]/div/div/a/i

</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fa fa-trash</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[4]/div/div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[4]/div/div/div[1]/div/div/a/i</value>
   </webElementProperties>
</WebElementEntity>
