<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>item_image</name>
   <tag></tag>
   <elementGuidId>163457ee-3c1b-423d-b80b-d7857833d33d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[1]/div/div/div[1]/div/div/div[1]/img[count(. | //img[@src = '/images/items/item-60148-636971095428527230-tZrRLs.jpg']) = count(//img[@src = '/images/items/item-60148-636971095428527230-tZrRLs.jpg'])]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[1]/div/div/div[1]/div/div/div[1]/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/images/items/item-59077-636963447625666143-PJj1O8.jpg</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[1]/div/div/div[1]/div/div/div[1]/img[count(. | //img[@src = '/images/items/item-60148-636971095428527230-tZrRLs.jpg']) = count(//img[@src = '/images/items/item-60148-636971095428527230-tZrRLs.jpg'])]</value>
   </webElementProperties>
</WebElementEntity>
