<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>LinkText_Dianne</name>
   <tag></tag>
   <elementGuidId>83c6cdbb-5fbb-4342-a595-9b2bed6d6f4a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//a[@href = '/user/order/comparison?comparisonId=ddf7d5e5-ad98-e911-80d2-000d3aa147ac' and @class = 'list-name']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[3]/div/div/div[1]/div[3]/table/tbody/tr/td[1]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/user/order/comparison?comparisonId=ddf7d5e5-ad98-e911-80d2-000d3aa147ac</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>list-name</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dianne</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//div[3]/div/div/div[1]/div[3]/table/tbody/tr/td[1]/a</value>
   </webElementProperties>
</WebElementEntity>
