<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textlabel_currency</name>
   <tag></tag>
   <elementGuidId>13dadd6c-b850-44f0-a1c0-b740e7bf6515</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div/div[1]/div/div[4]/div/div[2]/div[1]/div/div/div[1]/div/div/div[1]/div/div/div[3]/span[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>SGD</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;react_0HLNPQKOPV2AK&quot;)/div[1]/div[@class=&quot;cart-container&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row no-pad&quot;]/div[1]/div[@class=&quot;col-sm-10 col-xs-8&quot;]/div[@class=&quot;compare-slider slick-initialized slick-slider&quot;]/div[@class=&quot;slick-list draggable&quot;]/div[@class=&quot;slick-track&quot;]/div[@class=&quot;slick-slide slick-current slick-active&quot;]/div[1]/div[@class=&quot;col-sm-4&quot;]/div[1]/div[@class=&quot;cmparpg-list-td text-center&quot;]/div[@class=&quot;cmparpg-price&quot;]/span[1]</value>
   </webElementProperties>
</WebElementEntity>
