<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>checkbox_3.1.1</name>
   <tag></tag>
   <elementGuidId>7df11c86-c254-4a6b-b5f5-1435616d5583</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id=&quot;pcateglist&quot;]/li[3]/ul/li[1]/ul/li[1]/div/label</value>
   </webElementProperties>
</WebElementEntity>
