<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>link_url</name>
   <tag></tag>
   <elementGuidId>f7a5bf53-dfaa-4ddc-a7a8-d726348ade0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://u2507958.ct.sendgrid.net/wf/click?upn=llNWqR-2FTpI64syuC183dW8ERAZvAWRd-2BXuEZAIGLKjk4YqKUFnNzckm-2BXsveA2Na_-2FlVKhLauYRHm-2FC8Ownvq0PwwVxsfvOLahAVFSwBsMwl3S3XzaT1VIYOrnnv5Y6TwF-2BPsglc2dgZlbFUcMvfhb6wRuCwh6SQjqK5VitN5NdUVswfm3hMbd4bG54q2d8b37taexPu46oiYbuGKImojsl3BsKMuh523TztnpymufeX9yCVV0yTxjNr-2BWoI34R9EKn45efWsJkV5lAlFMRPTj1uEy-2FryU0RKem-2Fy8iK1L3o-3D</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>https://625un.test.arcadier.io</value>
   </webElementProperties>
</WebElementEntity>
